//
//  main.m
//  Counting DNA Nuclet
//
//  Created by asyl13 on 29.11.14.
//  Copyright (c) 2014 Asylzhan Salimkhan. All rights reserved.
//

#import <Foundation/Foundation.h>

#define NUCLEOTIDE_A 'A'
#define NUCLEOTIDE_G 'G'
#define NUCLEOTIDE_C 'C'
#define NUCLEOTIDE_T 'T'


int main(int argc, const char * argv[]) {
    @autoreleasepool {
        int counterA=0;
        int counterG=0;
        int counterC=0;
        int counterT=0;
        char character;
        NSString *s = @"GTCCGTAGAAGCCCGAGTAGTAATGGGCTGTGTCCCTACAGTCATAACCTGTGACACGGACTACGCTAAGCTCTGCTATCGGATATTTTGGGGGATGATCATCCACTCCCTTCGTACGGCTTCCATCTTTTAAAAGGACACAAGATATCTGTGACGGACTCCGGGCCCGGGCTAGGAAAGTTACAAAATCGACTCTCTACCAGCACCTATTGCTTTTCACCAGCTGTAGGCCGTATATTCTGGGCAGTGCTACAGAATATGCCACTATTGCGATCTCAGCTCTACTGGACACGAAGATGCTTATCTGCATTAGTGCTCTAATTGCGGAGTACGTCACCTTTTTATTCGCCATGAAACGGCAGCTTATTGGATCGTGCCGAGTTTAAAGACGAAACCAGTTAACTCGGGAATTGTAACTCATCTTCTAGCAGCGCCGCTTGGTCGCTCCCGGGAATAGTCCCACTCCCTATAGAACCTCGCCACTCTGCTCGGTGCTTCGCAAGCATTACAACGGTGACTTTACTCCGTAACGAAGCGCTCACGCGCTTGCACCCGTGTCAGGCTAACATTTGAAGTACGCACCAGTCTCAGCTTAGATTGATGACGATCTTTAAGGTGGATTTAGCTGACTGTCAGCCTAGTGAAAGTAGTCCCTTGAGCTTTAACGTTTAACGAAGCCTCGATTCGCAGCAAAGATGCTTTCTCTTGTCAGTGGCGAAAGCCGAACGCAGTAGTAACTAAACCTCCGCCGCGAGCACCAGGAAAAGGGGTAGTCCGGCGTACCAACAGCTGACTACTCAAGCACAGGGTCGGCTGTGATTGACGATTCTAACGACGTCGAAGCTACAACTAAGCCGCACGAAAGTACTCACCTCCGGCAGTACTCCCTCCTAGACGGCGGGTCATGCAGGTAATTCGATGGATGTAGTGCCCG";
        for (int i = 0; i < [s length]; i++) {
            character = [s characterAtIndex:i];
            if (character == NUCLEOTIDE_A) {
                counterA++;
            }
            else if (character == NUCLEOTIDE_G){
                counterG++;
            }
            else if (character == NUCLEOTIDE_C){
                counterC++;
            }
            else if (character == NUCLEOTIDE_T){
                counterT++;
            }
        }
        NSLog(@"%i %i %i %i", counterA, counterC, counterG, counterT);
    }
    return 0;
}